"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/contexts/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import { supabase } from "@/lib/supabase";
import { toast } from "react-hot-toast";
import Link from "next/link";
import {
  ArrowLeftIcon,
  PhotoIcon,
  TicketIcon,
  CalendarIcon,
  ClockIcon,
  MapPinIcon,
  TagIcon,
  CurrencyEuroIcon,
  InformationCircleIcon,
} from "@heroicons/react/24/outline";

const categories = [
  "Música",
  "Comida & Lifestyle",
  "Cultura & Arte",
  "Conferência & Negócios",
  "Universitário",
  "Desporto",
  "Teatro",
  "Festa",
  "Festival",
  "Workshop",
  "Outro",
];

export default function CreateEventPage() {
  return (
    <ProtectedRoute>
      <CreateEventContent />
    </ProtectedRoute>
  );
}

function CreateEventContent() {
  const { user } = useAuth();
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    eventDate: "",
    eventTime: "",
    location: "",
    category: "Música",
    basePrice: "",
  });

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setImagePreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      let imageUrl = null;

      // Upload image if selected
      if (imageFile) {
        const fileExt = imageFile.name.split(".").pop();
        const fileName = `${user?.id}/${Date.now()}.${fileExt}`;

        const { error: uploadError } = await supabase.storage
          .from("event-images")
          .upload(fileName, imageFile);

        if (uploadError) throw uploadError;

        const {
          data: { publicUrl },
        } = supabase.storage.from("event-images").getPublicUrl(fileName);

        imageUrl = publicUrl;
      }

      // Create event
      const { data, error } = await supabase
        .from("events")
        .insert({
          title: formData.title,
          slug: "", // Will be auto-generated by trigger
          description: formData.description,
          event_date: formData.eventDate,
          event_time: formData.eventTime,
          location: formData.location,
          category: formData.category,
          base_price: parseFloat(formData.basePrice),
          image_url: imageUrl,
          organizer_id: user?.id || "",
          association_code: "", // Will be auto-generated by trigger
        } as never)
        .select()
        .single();

      if (error) throw error;

      // Create organizer association
      await supabase.from("event_users").insert({
        event_id: (data as Record<string, string>)?.id,
        user_id: user?.id || "",
        role: "organizer",
      } as never);

      toast.success("Evento criado com sucesso!");
      router.push(`/events/${(data as Record<string, string>)?.slug}`);
    } catch (error: unknown) {
      console.error("Error creating event:", error);
      const errorMessage =
        error instanceof Error ? error.message : "Erro ao criar evento";
      toast.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >,
  ) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  return (
    <div className="min-h-screen bg-dark">
      {/* Navbar */}
      <nav className="navbar">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="flex items-center space-x-2 group">
              <TicketIcon className="h-8 w-8 text-primary-400 group-hover:text-primary-300 transition-colors" />
              <span className="text-2xl font-bold gradient-text">
                TicketHub
              </span>
            </Link>

            <div className="flex items-center space-x-6">
              <Link href="/events" className="nav-link">
                Ver Eventos
              </Link>
              <Link href="/dashboard" className="nav-link">
                Dashboard
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {/* Back Button */}
        <Link
          href="/dashboard"
          className="inline-flex items-center space-x-2 text-gray-400 hover:text-white mb-8 transition-colors group"
        >
          <ArrowLeftIcon className="h-5 w-5 group-hover:-translate-x-1 transition-transform" />
          <span>Voltar ao Dashboard</span>
        </Link>

        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold gradient-text mb-3">
            Criar Novo Evento
          </h1>
          <p className="text-gray-400 text-lg">
            Preencha os dados do seu evento e comece a vender bilhetes
          </p>
        </div>

        {/* Form Card */}
        <div className="card-dark p-6 sm:p-8 lg:p-10">
          <form onSubmit={handleSubmit} className="space-y-8">
            {/* Image Upload Section */}
            <div className="space-y-3">
              <label className="flex items-center text-base font-semibold text-white">
                <PhotoIcon className="h-5 w-5 mr-2 text-primary-400" />
                Imagem do Evento
              </label>
              <p className="text-sm text-gray-500">
                Adicione uma imagem atrativa para o seu evento
              </p>
              <div className="relative">
                {imagePreview ? (
                  <div className="relative rounded-xl overflow-hidden group">
                    <img
                      src={imagePreview}
                      alt="Preview"
                      className="w-full h-72 object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 flex items-center justify-center">
                      <button
                        type="button"
                        onClick={() => {
                          setImageFile(null);
                          setImagePreview(null);
                        }}
                        className="bg-red-500 hover:bg-red-600 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-200 transform hover:scale-105"
                      >
                        Remover Imagem
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="border-2 border-dashed border-gray-700 rounded-xl p-12 sm:p-16 text-center hover:border-primary-500 hover:bg-gray-800/30 transition-all duration-300 cursor-pointer">
                    <PhotoIcon className="mx-auto h-16 w-16 text-gray-600 mb-4" />
                    <div className="space-y-2">
                      <label
                        htmlFor="file-upload"
                        className="relative cursor-pointer"
                      >
                        <span className="text-primary-400 hover:text-primary-300 font-semibold text-lg">
                          Carregar ficheiro
                        </span>
                        <input
                          id="file-upload"
                          name="file-upload"
                          type="file"
                          className="sr-only"
                          accept="image/*"
                          onChange={handleImageChange}
                        />
                      </label>
                      <p className="text-gray-500">ou arraste e largue</p>
                    </div>
                    <p className="text-xs text-gray-600 mt-3">
                      PNG, JPG, GIF até 10MB • Recomendado: 1920x1080px
                    </p>
                  </div>
                )}
              </div>
            </div>

            {/* Divider */}
            <div className="border-t border-gray-800"></div>

            {/* Title */}
            <div className="space-y-3">
              <label
                htmlFor="title"
                className="block text-base font-semibold text-white"
              >
                Título do Evento <span className="text-red-400">*</span>
              </label>
              <input
                type="text"
                id="title"
                name="title"
                value={formData.title}
                onChange={handleChange}
                required
                className="input-dark text-lg"
                placeholder="Ex: Concerto de Verão 2025"
              />
            </div>

            {/* Description */}
            <div className="space-y-3 -mx-6 sm:-mx-8 lg:-mx-10 px-6 sm:px-8 lg:px-10">
              <label
                htmlFor="description"
                className="block text-base font-semibold text-white"
              >
                Descrição <span className="text-red-400">*</span>
              </label>
              <textarea
                id="description"
                name="description"
                value={formData.description}
                onChange={handleChange}
                required
                rows={10}
                className="input-dark w-full"
                placeholder="Descreva o seu evento de forma detalhada. Inclua informações sobre o que os participantes podem esperar, lineup, programação, etc."
              />
              <p className="text-sm text-gray-500">
                Mínimo de 50 caracteres recomendado
              </p>
            </div>

            {/* Divider */}
            <div className="border-t border-gray-800"></div>

            {/* Date and Time */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">
                Data e Hora
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-3">
                  <label
                    htmlFor="eventDate"
                    className="flex items-center text-base font-medium text-gray-300"
                  >
                    <CalendarIcon className="h-5 w-5 mr-2 text-primary-400" />
                    Data <span className="text-red-400 ml-1">*</span>
                  </label>
                  <input
                    type="date"
                    id="eventDate"
                    name="eventDate"
                    value={formData.eventDate}
                    onChange={handleChange}
                    required
                    className="input-dark"
                  />
                </div>
                <div className="space-y-3">
                  <label
                    htmlFor="eventTime"
                    className="flex items-center text-base font-medium text-gray-300"
                  >
                    <ClockIcon className="h-5 w-5 mr-2 text-primary-400" />
                    Hora <span className="text-red-400 ml-1">*</span>
                  </label>
                  <input
                    type="time"
                    id="eventTime"
                    name="eventTime"
                    value={formData.eventTime}
                    onChange={handleChange}
                    required
                    className="input-dark"
                  />
                </div>
              </div>
            </div>

            {/* Location */}
            <div className="space-y-3">
              <label
                htmlFor="location"
                className="flex items-center text-base font-semibold text-white"
              >
                <MapPinIcon className="h-5 w-5 mr-2 text-primary-400" />
                Localização <span className="text-red-400 ml-1">*</span>
              </label>
              <input
                type="text"
                id="location"
                name="location"
                value={formData.location}
                onChange={handleChange}
                required
                className="input-dark"
                placeholder="Ex: Altice Arena, Parque das Nações, Lisboa"
              />
              <p className="text-sm text-gray-500">
                Inclua o nome do local e a cidade
              </p>
            </div>

            {/* Divider */}
            <div className="border-t border-gray-800"></div>

            {/* Category and Price */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">
                Detalhes do Evento
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-3">
                  <label
                    htmlFor="category"
                    className="flex items-center text-base font-medium text-gray-300"
                  >
                    <TagIcon className="h-5 w-5 mr-2 text-primary-400" />
                    Categoria <span className="text-red-400 ml-1">*</span>
                  </label>
                  <select
                    id="category"
                    name="category"
                    value={formData.category}
                    onChange={handleChange}
                    required
                    className="input-dark"
                  >
                    {categories.map((cat) => (
                      <option key={cat} value={cat}>
                        {cat}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="space-y-3">
                  <label
                    htmlFor="basePrice"
                    className="flex items-center text-base font-medium text-gray-300"
                  >
                    <CurrencyEuroIcon className="h-5 w-5 mr-2 text-primary-400" />
                    Preço Base <span className="text-red-400 ml-1">*</span>
                  </label>
                  <div className="relative">
                    <input
                      type="number"
                      id="basePrice"
                      name="basePrice"
                      value={formData.basePrice}
                      onChange={handleChange}
                      required
                      min="0"
                      step="0.01"
                      className="input-dark pl-10"
                      placeholder="0.00"
                    />
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <span className="text-gray-500 text-lg">€</span>
                    </div>
                  </div>
                  <p className="text-sm text-gray-500">
                    Preço de entrada base (sem taxas)
                  </p>
                </div>
              </div>
            </div>

            {/* Info Box */}
            <div className="bg-gradient-to-r from-primary-500/10 to-blue-500/10 border border-primary-500/20 rounded-xl p-5">
              <div className="flex items-start space-x-3">
                <InformationCircleIcon className="h-6 w-6 text-primary-400 flex-shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <p className="text-sm font-semibold text-primary-300">
                    O que acontece depois?
                  </p>
                  <p className="text-sm text-gray-400">
                    Após criar o evento, você será redirecionado para o painel
                    de gestão onde poderá adicionar diferentes tipos de
                    bilhetes, definir quotas, configurar descontos e muito mais.
                  </p>
                </div>
              </div>
            </div>

            {/* Submit Buttons */}
            <div className="flex flex-col-reverse sm:flex-row gap-4 pt-6 border-t border-gray-800">
              <Link
                href="/dashboard"
                className="w-full sm:w-auto px-8 py-4 bg-gray-800 hover:bg-gray-700 text-white rounded-xl font-semibold transition-all duration-200 text-center border border-gray-700"
              >
                Cancelar
              </Link>
              <button
                type="submit"
                disabled={loading}
                className="btn-primary w-full sm:flex-1 py-4 text-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {loading ? (
                  <span className="flex items-center justify-center">
                    <svg
                      className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      ></circle>
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                    A criar evento...
                  </span>
                ) : (
                  "Criar Evento"
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
